services:
  nginx:
    image: nginx:alpine
    container_name: minha_agenda_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www:delegated
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - redis
      - postgresql
    networks:
      - laravel
    restart: unless-stopped

  postgresql: 
    image: postgres:16.4
    container_name: minha_agenda_postgres
    environment: 
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - ./docker/postgres/data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - laravel
    restart: unless-stopped

  php:
    container_name: minha_agenda_php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www:delegated
    networks:
      - laravel
    restart: unless-stopped  

  redis:
    container_name: minha_agenda_redis
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis/data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
    networks:
      - laravel
    restart: unless-stopped
  

volumes:
  postgresql: 
    driver: local

networks:
  laravel:
    driver: bridge